services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: peliculas_db
      POSTGRES_USER: user_demo
      POSTGRES_PASSWORD: pass_demo
    ports:
      - "5433:5432"

  app:
    build: .
    container_name: spring_api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/peliculas_db