spring.application.name=demo

# Configuración para conectar con el contenedor de base de datos
spring.datasource.url=jdbc:postgresql://db:5432/peliculas_db
spring.datasource.username=user_demo
spring.datasource.password=pass_demo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true